### PR TITLE
Add getSupportedLocales() and getAllCountriesForLocale()

### PR DESCRIPTION
**Pull request by giggsey**
Additional functionality requested in https://github.com/ACP3/cms/issues/57

### CODE REVIEW

**Comment by giggsey** [comment]
@tinogo How do these functions look? Do they provide what you need?

**Comment by tinogo** [comment]
@giggsey Nice - Looking good to me! :)

**Comment by giggsey** [comment]
Thanks.

There was a commit recently to the CLDR project, so I expect a new version of that will be released shortly. Once it is, I'll tag this as 1.3

**Comment by giggsey** [comment]
`getAllCountriesForLocale` doesn't work as expected for countries that have 'sub' locales.

E.g. es-bz was just added to the CLDR data list. However, it doesn't have a data file itself, because the contents are identical to es. Currently `getAllCountriesForLocale()` will error if we call this.

I'll make it fallback to the 'top-level' country, merging the array as needed.

**Pull request merged**
