### PR TITLE
Ignore files when exporting package

### PR DESCRIPTION
**Pull request by simonschaufi**
This commit is part of a campaign to reduce the amount of data transferred to save global bandwidth and reduce the amount of CO2. See https://github.com/Codeception/Codeception/pull/5527 for more info.

### CODE REVIEW

**Comment by giggsey** [comment]
Thanks. I'm going to extend it a bit further, and exclude other files that aren't needed. I'll also add the exclusion to composer.json (see https://github.com/giggsey/libphonenumber-for-php/blob/master/composer.json#L46)

**Comment by simonschaufi** [comment]
Is the section within composer.json handled differently than .gitattributes? I have never seen anyone excluding files within composer.json

**Comment by giggsey** [comment]
https://getcomposer.org/doc/04-schema.md#archive

I think if Composer generates the archive file itself from source, rather than using GitHub, then I think it uses that archive config.

**Comment by simonschaufi** [comment]
> I think if Composer generates the archive file itself from source

I would like to know in which case that happens. Do you have an idea?

**Comment by giggsey** [comment]
> > I think if Composer generates the archive file itself from source
> 
> I would like to know in which case that happens. Do you have an idea?

I used to think when Satis was generating an archive from non GitHub, but I've just tried it at $work, and it's excluded the build & tests directory. Maybe Composer doesn't make use of it separately anymore.

**Comment by simonschaufi** [comment]
ok

**Pull request merged**
